### ISSUE TITLE
RFC 8551 compliance?

### ISSUE THREAD

**Issue by robert-scheck** [svenbs/mailenc#1]
Do you have any plans for [RFC 8551](https://tools.ietf.org/html/rfc8551) compliance? The currently used Triple DES is considered [weak encryption](https://tools.ietf.org/html/rfc8551#section-2.7.2). While reading [§ 2.7.1](https://tools.ietf.org/html/rfc8551#section-2.7.1), it might be a good idea to make this configurable per recipient and/or recipient domain (maybe using similar like tables in Postfix)?

**Comment by svenbs** [comment]
@robert-scheck : That's correct. Even though I'm not actively developing the project, I've made a correction. Thank you for your hint.
